version: '2'

services:
  redis:
    networks:
      - dev
    dns:
      172.28.0.2
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  dev:
    external: true