services:
  ollama:
    networks:
      - dev
    dns:
      172.28.0.2
    image: ollama/ollama:0.1.34
    ports:
      - "11434:11434"
    volumes:
      - .volumes/ollama:/root/.ollama

networks:
  dev:
    external: true
